<?php
/**
 * SCRIPT DI RIPRISTINO E AGGIORNAMENTO CONTENUTI ENHANCED
 * Eseguire questo script dal browser: http://localhost/fix_content.php
 */

require_once 'includes/db_connect.php';

echo "<h2>Avvio ripristino e potenziamento contenuti...</h2>";

try {
    // 1. Assicuriamoci che la colonna esista
    echo "Verifica struttura database... ";
    try {
        $pdo->exec("ALTER TABLE services ADD COLUMN short_description TEXT AFTER name");
        echo "<span style='color:green'>Colonna aggiunta.</span><br>";
    } catch (PDOException $e) {
        if ($e->getCode() == '42S21') {
            echo "<span style='color:orange'>Colonna già presente.</span><br>";
        } else {
            throw $e;
        }
    }

    // 2. Mappa dei contenuti (Versione breve e lunga ENHANCED)
    $updates = [
        'assemblaggio-pc' => [
            'short' => 'Progettiamo e assembliamo il tuo computer ideale. Dalle potenti workstation per professionisti ai PC gaming più estremi, curiamo ogni dettaglio hardware.',
            'long' => "Il nostro servizio di assemblaggio PC offre una consulenza tecnica completa e personalizzata per creare una macchina che rispecchi perfettamente le tue reali necessità, siano esse professionali o ludiche. Non ci limitiamo a montare i componenti: partiamo da un'analisi approfondita delle tue abitudini di utilizzo per selezionare l'hardware con il miglior rapporto qualità-prezzo e la massima longevità.\n\nStudiamo minuziosamente il bilanciamento tra CPU e GPU per evitare colli di bottiglia, ottimizziamo il flusso d'aria interno (airflow) per garantire temperature operative basse anche sotto carico e gestiamo il cablaggio in modo maniacale per un'estetica pulita e una facile manutenzione. Che tu abbia bisogno di una workstation per il montaggio video in 8K, per il calcolo scientifico complesso o di un PC gaming di fascia alta pronto per il 4K a 144Hz, garantiamo test di stabilità rigorosi di 24 ore e profili BIOS personalizzati per estrarre ogni briciola di performance in totale sicurezza. Utilizziamo solo paste termiche di altissima qualità e componenti dei brand più affidabili sul mercato."
        ],
        'riparazione-console' => [
            'short' => 'Assistenza rapida per PS5, Xbox e Nintendo. Ripariamo porte HDMI, lettori, joy-con e problemi di surriscaldamento per farti tornare a giocare subito.',
            'long' => "Siamo il punto di riferimento a Legnano per la riparazione professionale di console da gioco di ultima e penultima generazione, incluse PlayStation 5, Xbox Series X/S e Nintendo Switch. I nostri tecnici intervengono con precisione su guasti hardware complessi che richiedono micro-saldature, come la sostituzione di chip video (Encoder IC), porte HDMI danneggiate o connettori USB-C.\n\nOffriamo inoltre un servizio essenziale di manutenzione preventiva: la pulizia interna profonda unita alla sostituzione della pasta termica o, nel caso di PS5, del metallo liquido. Questo intervento è fondamentale per prevenire spegnimenti improvvisi, rallentamenti (thermal throttling) e il fastidioso rumore eccessivo delle ventole, allungando drasticamente la vita della tua console. Gestiamo anche i problemi comuni dei controller, come l'analog drift dei Joy-Con o dei DualSense, e i guasti ai lettori ottici che non leggono più i dischi. Ogni riparazione viene testata con stress-test dedicati per garantirti ore di gioco senza interruzioni."
        ],
        'servizi-digitali' => [
            'short' => 'Supporto completo per la tua vita digitale: attivazione SPID, configurazione PEC, firma digitale e assistenza per la burocrazia online.',
            'long' => "Navigare tra i portali della Pubblica Amministrazione e gestire le nuove identità digitali può essere un'esperienza frustrante e complessa. Il nostro servizio di assistenza digitale nasce per semplificarti la vita, offrendoti un supporto passo-passo nell'attivazione e nell'utilizzo degli strumenti tecnologici ormai indispensabili nella vita quotidiana e professionale.\n\nTi guidiamo nell'attivazione dello SPID (Sistema Pubblico di Identità Digitale), configuriamo la tua Posta Elettronica Certificata (PEC) su computer e smartphone e ti assistiamo nell'installazione dei kit di Firma Digitale. Forniamo supporto diretto per l'accesso e la navigazione sui portali INPS, Agenzia delle Entrate (cassetto fiscale), Fascicolo Sanitario Elettronico e portali comunali per pratiche burocratiche. Che tu debba scaricare un certificato, presentare una domanda di bonus o semplicemente gestire le tue credenziali in sicurezza, i nostri esperti sono al tuo fianco per eliminare ogni barriera tecnologica, garantendoti rapidità e massima riservatezza dei tuoi dati sensibili."
        ],
        'consulenza-acquisto' => [
            'short' => 'Non sprecare soldi in acquisti sbagliati. Ti aiutiamo a scegliere il miglior PC, notebook o tablet in base al tuo budget e utilizzo reale.',
            'long' => "Il mercato dell'elettronica è saturato da migliaia di modelli che sembrano tutti uguali ma nascondono differenze tecniche abissali. Con il nostro servizio di consulenza all'acquisto professionale, il nostro obiettivo è farti risparmiare denaro evitandoti di comprare prodotti sovradimensionati per le tue esigenze o, peggio, dispositivi economici che diventerebbero obsoleti in pochi mesi.\n\nAnalizziamo nel dettaglio le tue abitudini: se sei uno studente che ha bisogno di portabilità e autonomia, un professionista che necessita di potenza di calcolo o un utente domestico che cerca semplicità e affidabilità. Ti indichiamo esattamente quali specifiche osservare (tipologia di processore, quantità e velocità della RAM, qualità del display e tecnologia del disco fisso) e setacciamo i migliori store online e fisici per trovare l'offerta più vantaggiosa del momento. Ti aiutiamo inoltre a scegliere gli accessori giusti, dalle periferiche di input ai sistemi di backup, assicurandoti un ecosistema tecnologico armonioso, efficiente e duraturo nel tempo."
        ],
        'contenuti-ai' => [
            'short' => 'Sfrutta la potenza dell\'Intelligenza Artificiale per la tua attività. Generiamo testi creativi, immagini e soluzioni di automazione intelligenti.',
            'long' => "L'Intelligenza Artificiale non è più il futuro, è il presente della produttività aziendale e creativa. Aiutiamo professionisti, piccole imprese e creativi a integrare i più avanzati strumenti di AI nel proprio flusso di lavoro quotidiano per ottenere risultati straordinari in una frazione del tempo abituale. Offriamo un servizio di copywriting assistito da AI per la creazione di articoli blog ottimizzati SEO, post per i social media che catturano l'attenzione e descrizioni prodotto efficaci.\n\nSul fronte visuale, sfruttiamo modelli di generazione d'immagine per creare asset grafici unici, realistici o artistici, perfetti per il tuo marketing senza costi di produzione elevati. Ma non ci fermiamo alla generazione di contenuti: ti offriamo consulenza strategica su come utilizzare strumenti come ChatGPT, Claude o Midjourney per automatizzare compiti ripetitivi, gestire la customer care o analizzare grandi volumi di dati. Insegniamo ai tuoi dipendenti come redigere 'prompt' efficaci, trasformando l'AI in un potente acceleratore per il tuo business, mantenendo sempre un tocco umano per la revisione finale e la strategia."
        ],
        'creazioni-grafiche' => [
            'short' => 'Diamo un volto professionale al tuo brand. Realizziamo loghi, biglietti da visita, brochure e grafiche coordinate per social e web.',
            'long' => "L'identità visiva è la prima forma di comunicazione tra te e i tuoi potenziali clienti. Un brand coerente e professionale trasmette fiducia e competenza istantaneamente. Il nostro servizio di progettazione grafica si occupa di costruire o rinnovare l'immagine coordinata della tua attività, partendo dallo studio del logo: realizziamo marchi vettoriali unici, versatili e memorabili, capaci di funzionare sia su una piccola icona social che su un'insegna di grandi dimensioni.\n\nCi occupiamo poi del declinare questa identità su tutto il materiale necessario: biglietti da visita stampati su carte di pregio, brochure informative, volantini promozionali e cataloghi prodotti. Non trascuriamo il mondo digitale: progettiamo template per i tuoi post su Instagram e Facebook, banner per il tuo sito web e presentazioni aziendali che lasciano il segno. Ogni progetto viene curato nella scelta dei colori, delle font e dello stile per assicurare che ogni punto di contatto con il tuo pubblico racconti la stessa storia di qualità e professionalità."
        ],
        'ripristino-so' => [
            'short' => 'Il tuo PC è bloccato o lentissimo? Reinstalliamo Windows, macOS o Linux salvando i tuoi dati e configurando tutto per un riavvio perfetto.',
            'long' => "Con il passare del tempo, ogni computer tende ad accumulare errori di sistema, file obsoleti e conflitti tra driver che lo rendono lento e instabile. Quando la normale manutenzione non basta più, il ripristino profondo è l'unica soluzione per ridare al tuo dispositivo la velocità del primo giorno. Il nostro servizio di installazione pulita del Sistema Operativo è completo e meticoloso: iniziamo con un backup ridondante di tutti i tuoi documenti, foto e impostazioni personali per garantirti la totale sicurezza dei dati.\n\nProcediamo poi con la formattazione sicura dell'unità disco e l'installazione dell'ultima versione più stabile di Windows, macOS o della tua distribuzione Linux preferita. Non ci limitiamo all'installazione base: scarichiamo e configuriamo manualmente ogni singolo driver hardware per garantire la perfetta compatibilità con stampanti, schede audio professionali e monitor ad alta risoluzione. Infini, reinstalliamo i programmi software essenziali (browser, suite Office, antivirus) e ripristiniamo i tuoi dati, consegnandoti un computer fluido, reattivo, privo dei programmi inutili (bloatware) preinstallati dai produttori e pronto per affrontare nuove sfide."
        ],
        'software-antivirus' => [
            'short' => 'Installazione programmi professionali e protezione totale contro virus, malware e cyber-attacchi. Metti al sicuro i tuoi dati preziosi.',
            'long' => "Un hardware potente è inutile senza il software giusto e, soprattutto, senza una protezione adeguata. Il nostro servizio si occupa di rendere il tuo computer uno strumento di lavoro completo e sicuro. Gestiamo l'installazione e la configurazione ottimale di pacchetti professionali come Microsoft Office, suite di grafica Adobe, software di contabilità o strumenti di sviluppo. Ci assicuriamo che ogni programma sia aggiornato e correttamente licenziato, evitando problemi di crash o incompatibilità.\n\nIl pilastro fondamentale è però la nostra consulenza sulla Cybersecurity. Non installiamo un antivirus qualunque: selezioniamo le suite di protezione più leggere ed efficaci, capaci di bloccare non solo i virus tradizionali ma anche i pericolosissimi Ransomware e i tentativi di Phishing. Configuriamo Firewall avanzati e sistemi di scansione in tempo reale, ed educhiamo l'utente sulle migliori pratiche per navigare sicuri. Proteggiamo i tuoi dati aziendali o le tue foto di famiglia crittografando le cartelle sensibili e impostando sistemi di backup automatici, perché la sicurezza informatica non si vede finché non serve, ma quando serve deve essere impeccabile."
        ],
        'siti-web' => [
            'short' => 'La tua vetrina online professionale. Creiamo siti web moderni, veloci e ottimizzati per Google per farti trovare dai tuoi clienti.',
            'long' => "Oggi non possedere un sito web significa essere invisibili per una fetta enorme di potenziali clienti. Ma non basta avere un sito: deve essere veloce, intuitivo e capace di convertire i visitatori in contatti reali. Progettiamo soluzioni web su misura, dalle eleganti 'One Page' per liberi professionisti che vogliono una presenza immediata, ai siti vetrina aziendali più articolati, fino a piattaforme e-commerce ottimizzate per la vendita.\n\nOgni nostro sito è rigorosamente 'Responsive', ovvero studiato per adattarsi perfettamente a ogni schermo, con una priorità assoluta per la navigazione da smartphone. Curiamo maniacalmente le performance: un sito rapido non solo offre un'esperienza migliore all'utente, ma è premiato da Google nei risultati di ricerca. Includiamo sempre un'ottimizzazione SEO di base sulla struttura e sui contenuti per darti la massima visibilità locale e globale. Ti forniamo inoltre una formazione rapida per permetterti di aggiornare testi e immagini in totale autonomia, restando sempre al tuo fianco per manutenzione, aggiornamenti di sicurezza e strategie di web marketing per far crescere il tuo business online."
        ],
        'recupero-dati' => [
            'short' => 'Recuperiamo i tuoi ricordi e documenti importanti da Hard Disk rotti, chiavette USB danneggiate e schede di memoria non funzionanti.',
            'long' => "La perdita di dati importanti, che siano ricordi di famiglia o documenti aziendali critici, è un momento di grande stress. Un file cancellato per errore, un'unita formattata per sbaglio o un Hard Disk che emette rumori strani ed è illeggibile non indicano necessariamente una perdita definitiva. Interveniamo con successo su una vasta gamma di supporti: Hard Disk meccanici (sia esterni che interni), moderni dischi a stato solido (SSD), chiavette USB danneggiate fisicamente e schede di memoria SD/MicroSD corrotta.\n\nUtilizziamo software di recupero forense professionale capace di ricostruire le tabelle dei file anche in casi di grave corruzione logica. Nei casi di danno fisico minore, come connettori dissaldati o componenti della logica (PCB) bruciati, eseguiamo interventi di riparazione elettronica per permettere l'estrazione dei dati. Seguiamo protocolli rigidi per non stressare ulteriormente i supporti fragili e garantiamo la massima riservatezza sui contenuti recuperati. Il nostro processo prevede una diagnosi iniziale gratuita per valutare le reali probabilità di recupero e una quotazione trasparente: nel caso in cui i dati non siano tecnicamente recuperabili, non dovrai affrontare spese eccessive."
        ],
        'pulizia-sicurezza' => [
            'short' => 'Rimozione virus e pulizia interna del computer. Eliminiamo polvere e file inutili per evitare surriscaldamenti e rallentamenti.',
            'long' => "La polvere è il nemico numero uno dell'elettronica, ma spesso viene trascurata. All'interno di ogni computer o notebook, l'accumulo di sporco ostruisce le ventole e i canali di areazione, causando picchi di calore che degradano i componenti e costringono il sistema a rallentare per non bruciarsi. Il nostro servizio di manutenzione profonda inizia con una pulizia hardware accurata: utilizziamo strumenti professionali per rimuovere ogni traccia di polvere dai dissipatori e dalle schede madri, ridando respiro ai componenti critici.\n\nContemporaneamente, eseguiamo una pulizia software meticolosa: scansioni profonde con strumenti anti-malware rintracciano e rimuovono adware, bloatware e programmi spia che rallentano la navigazione e mettono a rischio la tua privacy. Ottimizziamo l'avvio del sistema disabilitando i processi inutili e puliamo il registro di sistema e le cache di sistema per liberare spazio su disco e migliorare la reattività generale. È il servizio ideale da eseguire almeno una volta all'anno per garantire che il tuo investimento tecnologico resti affidabile, scattante e silenzioso come il primo giorno, prevenendo guasti hardware molto più costosi in futuro."
        ],
        'riparazione-pc' => [
            'short' => 'Diagnosi e riparazione hardware/software per ogni tipo di computer. Risolviamo guasti alla scheda madre, alimentatori e periferiche.',
            'long' => "Il nostro centro è specializzato nella risoluzione di qualsiasi problematica affligga il tuo personal computer, sia esso un desktop da ufficio, un PC gaming ad alte prestazioni o un notebook aziendale. Operiamo a 360 gradi: dai guasti hardware evidenti come alimentatori esplosi, schede video che mostrano artefatti o schede madri che non danno segni di vita, fino ai problemi software più subdoli come schermate blu improvvise (BSOD), errori di sistema incomprensibili o periferiche che smettono di funzionare.\n\nIniziamo ogni intervento con una diagnosi accurata utilizzando strumenti diagnostici di livello industriale per identificare con certezza la causa del problema, evitando sostituzioni di pezzi inutili. Siamo in grado di eseguire riparazioni elettroniche sulla scheda madre (come la sostituzione di condensatori o chip secondari) per evitare il costo proibitivo di una sostituzione completa. Ci occupiamo anche dei componenti strutturali: cerniere rotte nei portatili, ventole rumorose o connettori di ricarica lenti. Ogni nostra riparazione segue standard di qualità elevati e viene testata accuratamente prima della consegna per assicurarti una soluzione duratura e affidabile, con una garanzia chiara sull'intervento effettuato."
        ],
        'smaltimento' => [
            'short' => 'Smaltiamo correttamente il tuo vecchio materiale elettronico (RAEE) proteggendo l\'ambiente e cancellando i tuoi dati personali.',
            'long' => "Smaltire correttamente un vecchio computer, una stampante o uno smartphone non è solo un obbligo di legge, ma un dovere verso l'ambiente. I rifiuti elettronici (RAEE) contengono metalli pesanti e sostanze tossiche che, se gettati nel secco o nelle discariche comuni, inquinano gravemente il suolo e le falde acquifere. Il nostro servizio di smaltimento assistito si occupa di raccogliere il tuo vecchio materiale tecnologico e avviarlo verso canali di riciclo certificati che recuperano materiali preziosi come rame, oro e plastica.\n\nUn aspetto critico che molti trascurano è la sicurezza dei dati: un computer rottamato senza precauzioni è una miniera d'oro per i ladri d'identità. Per questo, prima di ogni smaltimento, eseguiamo obbligatoriamente un 'Data Wiping' forense sugli Hard Disk e sulle memorie interne: questa procedura sovrascrive i dati più volte, rendendo tecnicamente impossibile il recupero di qualsiasi tua foto, documento o password residua anche utilizzando tecniche di laboratorio. Ti offriamo un servizio comodo, ecologico e soprattutto sicuro, sollevandoti da ogni preoccupazione."
        ],
        'schermi-batterie' => [
            'short' => 'Sostituzione display notebook e smartphone. Cambiamo la tua batteria vecchia o gonfia per ridare autonomia ai tuoi dispositivi.',
            'long' => "Schermo rotto o batteria che dura pochi minuti? Non è necessario cambiare l'intero dispositivo. Siamo esperti nella sostituzione di pannelli display per notebook di ogni marca e per i principali modelli di smartphone e tablet sul mercato. Un display danneggiato, oltre ad essere fastidioso, può nascondere rischi di ulteriori danni interni o perdita di cristalli liquidi: interveniamo con precisione utilizzando schermi di ricambio certificati con garanzia su risoluzione, luminosità e fedeltà cromatica.\n\nAltrettanto importante è il servizio di sostituzione batterie. Con l'uso, le batterie al litio moderne (spesso integrate e non rimovibili facilmente) subiscono un degrado naturale o, peggio, possono gonfiarsi mettendo a rischio l'integrità del telaio e la sicurezza dell'utente. Sostituiamo le batterie esauste con ricambi di alta qualità che rispettano le specifiche di voltaggio e capacità originali, ridando al tuo portatile o smartphone l'autonomia di cui avevi bisogno per lavorare o studiare in mobilità. Effettuiamo inoltre il controllo dei cicli di carica e verifichiamo che il sistema di ricarica del dispositivo sia perfettamente funzionante per prevenire nuovi problemi."
        ],
        'upgrade-pc' => [
            'short' => 'Potenzia il tuo computer con dischi SSD e più memoria RAM. Prestazioni raddoppiate senza cambiare il tuo attuale PC.',
            'long' => "Non è sempre necessario spendere centinaia di euro per un computer nuovo: molto spesso, il tuo attuale PC è solo vittima di componenti ormai lenti che fanno da collo di bottiglia. Il nostro servizio di upgrade è la soluzione più intelligente ed economica per raddoppiare, o persino triplicare, la reattività del tuo computer. L'intervento principe è il passaggio dal vecchio Hard Disk meccanico (HDD) a un moderno Disco a Stato Solido (SSD): la differenza è abissale, con tempi di accensione che passano dai minuti ai pochi secondi.\n\nIntegriamo inoltre l'aumento della memoria RAM, fondamentale per chi lavora con molte schede del browser aperte contemporaneamente o con programmi più pesanti come gestionali o software di video-call. Analizziamo le specifiche tecniche della tua scheda madre per identificare il massimo potenziale di espansione possibile, consigliandoti i componenti più stabili e veloci. È un intervento rapido, che non richiede la perdita dei tuoi file e che può far vivere al tuo PC altri 4-5 anni di onorato servizio con prestazioni scattanti superiori a molti computer economici attualmente in vendita nei centri commerciali."
        ],
        'vendita-accessori' => [
            'short' => 'Ampia scelta di cavi, alimentatori, mouse, borse e periferiche esterne. Tutto ciò che serve per completare la tua postazione IT.',
            'long' => "La postazione informatica ideale non è fatta solo del computer, ma da tutto l'ecosistema di accessori che lo circonda. Presso il nostro punto o tramite il nostro catalogo dedicato, selezioniamo solo accessori e periferiche di grado professionale che garantiscono affidabilità e performance. Trovi tutto ciò che serve: dai cavi certificati di ogni standard (HDMI, USB-C ad alta velocità, cavi di rete Cat.6) agli alimentatori universali o specifici per notebook, fondamentali per evitare danni alla batteria causati da prodotti economici di scarsa qualità.\n\nOffriamo una vasta scelta di periferiche di input: tastiere ergonomiche per evitare problemi alle articolazioni, mouse ad alta precisione e tavolette grafiche. Per chi lavora in mobilità, disponiamo di borse e zaini protettivi imbottiti e hub USB eleganti e funzionali. Ogni accessorio che vendiamo è stato testato dai nostri tecnici per assicurarci che rispetti gli standard costruttivi necessari. La nostra missione è fornirti la soluzione giusta, consigliandoti il prodotto che realmente serve alla tua configurazione per massimizzare la tua produttività o il tuo divertimento."
        ],
        'vendita-pc' => [
            'short' => 'Computer nuovi e ricondizionati con garanzia. Ti guidiamo nella scelta della macchina perfetta già pronta all\'uso.',
            'long' => "Vuoi un computer nuovo ma non sai cosa scegliere? O cerchi un affare con un usato garantito? Offriamo una selezione curata di computer desktop e notebook per ogni esigenza. I nostri computer 'Nuovi Pronti all'Uso' non sono come quelli dei centri commerciali: li configuriamo noi personalmente prima della consegna, rimuovendo tutto il software pubblicitario inutile e installando solo ciò che serve per un'esperienza fluida e immediata. Sono macchine selezionate per la qualità dei materiali e la facilità di riparazione futura.\n\nGrande successo ha poi la nostra linea di 'Ricondizionati Professionali': si tratta di macchine di fascia alta (serie Business, workstation fisse) provenienti da fine noleggio o leasing. Questi computer, costruiti con standard qualitativi superiori, vengono da noi ispezionati minuziosamente, potenziati con nuovi SSD e RAM dove necessario, e venduti a un prezzo che è spesso la metà del loro valore originale da nuovi. Ogni nostro prodotto, nuovo o ricondizionato, è coperto da una garanzia reale e dal nostro supporto diretto: in caso di problemi, non dovrai parlare con un call center anonimo, ma verrai direttamente nel nostro laboratorio per un'assistenza rapida e risolutiva."
        ],
        'assistenza-stampanti' => [
            'short' => 'Riparazione e configurazione di stampanti laser e inkjet. Risolviamo inceppamenti di carta, problemi di rete e qualità stampa.',
            'long' => "Le stampanti sono famose per smettere di funzionare proprio quando ne hai più bisogno. Il nostro servizio di assistenza stampanti copre sia i modelli domestici inkjet che le più complesse macchine laser da ufficio. Interveniamo su inceppamenti meccanici ostinati, errori di comunicazione tra PC e stampante e problemi qualitativi come strisce nere sui fogli o colori mancanti dovuti a testine otturate o sensori sporchi. Spesso un intervento di pulizia profonda e taratura è sufficiente a salvare la tua stampante senza doverne acquistare una nuova.\n\nSiamo molto forti anche sul lato connettività: configuriamo stampe wireless e scansioni dirette via email o cartelle di rete (SMB), permettendo a tutti i computer, smartphone e tablet dell'ufficio o della casa di stampare senza dover collegare cavi. Ti offriamo inoltre consulenza sulla gestione dei materiali di consumo, consigliandoti come ottimizzare i costi utilizzando toner o cartucce ad alta resa o compatibili certificate che non danneggiano i meccanismi interni. Ti aiutiamo a risolvere ogni conflitto di driver e ogni errore del server di stampa, restituendo efficienza al tuo flusso di lavoro documentale."
        ]
    ];

    echo "Aggiornamento testi dei servizi con descrizione estesa (SEO ready)...<br>";
    $stmt = $pdo->prepare("UPDATE services SET short_description = :short, description = :long WHERE slug = :slug");

    foreach ($updates as $slug => $content) {
        $stmt->execute([
            ':short' => $content['short'],
            ':long' => $content['long'],
            ':slug' => $slug
        ]);
        echo " - Servizio $slug: <span style='color:green'>POTENZIATO</span><br>";
    }

    echo "<h3>Tutto completato con successo!</h3>";
    echo "<p>I contenuti sono stati ampliati in modo significativo per migliorare il dettaglio e l'SEO delle pagine interne.</p>";
    echo "<p><a href='/'>Torna alla Home</a></p>";

} catch (Exception $e) {
    echo "<h3 style='color:red'>ERRORE: " . $e->getMessage() . "</h3>";
}
?>